### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by zyf0330** [gtamas/etcdmanager#7]
**App and environment info (please complete the following information):**
 - OS: Ubuntu
 - OS version: 19.10
 - ETCD manager version: 1.0.0

**How can we help?.**

I use snap to install, but when open it, nothing happens. There is no window, no process like I doesn't open it.

**Comment by welsen** [comment]
@zyf0330 could you check, if the build was successful, and you can start the application from `etcdmanager/dist_electron/linux-unpacked`.

```
$ ./etcd-manager
```
or
```
$ ./etcd-manager --no-sandbox
```

**Comment by zyf0330** [comment]
Execute file is located at /snap/bin/etcd-manager, and these two commands
don't work.
Or do you mean I shoud try build by myself to test?

David Onofer <notifications@github.com> 于2019年12月3日周二 下午5:57写道：

**Comment by welsen** [comment]
@zyf0330 thanks, yes I'd suggest you build it yourself, and check if the problem remains.

just installed an Ubuntu 19.10 to test if snap install is fine, and had no problem running the app.

**Comment by zyf0330** [comment]
I run `yarn` and build fail, building grpc with electron fails.
```
yarn install v1.19.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > sass-loader@8.0.0" has unmet peer dependency "webpack@^4.36.0".
warning " > tslint-config-airbnb@5.11.2" has unmet peer dependency "tslint@^5.11.0".
warning "tslint-config-airbnb > tslint-consistent-codestyle@1.15.1" has unmet peer dependency "tslint@^5.0.0".
warning "tslint-config-airbnb > tslint-eslint-rules@5.4.0" has unmet peer dependency "tslint@^5.0.0".
warning "tslint-config-airbnb > tslint-microsoft-contrib@5.2.1" has unmet peer dependency "tslint@^5.1.0".
warning "tslint-config-airbnb > tslint-consistent-codestyle > @fimbul/bifrost@0.17.0" has unmet peer dependency "tslint@^5.0.0".
[5/5] Building fresh packages...
$ npx electron-builder install-app-deps
  • electron-builder  version=21.2.0
  • rebuilding native dependencies  dependencies=grpc@1.24.2, grpc@1.22.2 platform=linux arch=x64
  • rebuilding native dependency  name=grpc version=1.22.2
  • rebuilding native dependency  name=grpc version=1.24.2
  ⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.19.2
    $ node-pre-gyp install --fallback-to-build --library=static_library
    make: Entering directory '/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/build'
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_trace.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz_registry.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/status_util.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_args.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_internal.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/message_compress.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_gzip.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_identity.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats_data.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/format_request.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/httpcli.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/parser.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/buffer_list.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/call_combiner.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/cfstream_handle.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/combiner.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_cfstream.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_uv.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/error.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/error_cfstream.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_epoll1_linux.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_epollex_linux.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_poll_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/ev_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/exec_ctx.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/executor.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/fork_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/fork_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/gethostname_fallback.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/gethostname_host_name_max.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/gethostname_sysconf.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/grpc_if_nametoindex_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/grpc_if_nametoindex_unsupported.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/internal_errqueue.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iocp_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_custom.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_internal.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_posix_cfstream.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_uv.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/iomgr_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/is_epollexclusive_available.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/load_file.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/lockfree_event.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/polling_entity.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_custom.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_set.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_set_custom.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_set_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_uv.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/pollset_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_custom.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resolve_address_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/resource_quota.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/sockaddr_utils.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_factory_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_mutator.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_common_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_linux.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_uv.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_utils_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/socket_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_client.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_client_cfstream.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_client_custom.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_client_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_client_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_custom.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_custom.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_utils_posix_ifaddrs.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_utils_posix_noifaddrs.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_server_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_uv.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/tcp_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/time_averaged_stats.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer_custom.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer_generic.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer_heap.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer_manager.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/timer_uv.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/udp_server.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/unix_sockets_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/unix_sockets_posix_noop.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/wakeup_fd_eventfd.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/wakeup_fd_nospecial.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/wakeup_fd_pipe.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/wakeup_fd_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/json/json.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/json/json_reader.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/json/json_string.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/json/json_writer.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/b64.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/percent_encoding.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/slice.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/slice_buffer.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/slice_intern.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/slice/slice_string_helpers.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/api_trace.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/byte_buffer.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/byte_buffer_reader.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/call.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/call_details.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/call_log_batch.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/channel.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/channel_init.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/channel_ping.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/channel_stack_type.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/completion_queue.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/completion_queue_factory.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/event_string.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/lame_client.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/metadata_array.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/server.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/validate_metadata.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/version.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/bdp_estimator.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/byte_stream.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/connectivity_state.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/error_utils.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/metadata.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/metadata_batch.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/pid_controller.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/static_metadata.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/status_conversion.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/status_metadata.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/timeout_encoding.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/transport.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/transport/transport_op_string.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/uri/uri_parser.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/trace.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/bin_decoder.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/bin_encoder.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_plugin.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/context_list.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/flow_control.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/frame_data.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/frame_goaway.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/frame_ping.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/frame_rst_stream.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/frame_settings.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/frame_window_update.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/hpack_encoder.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/hpack_parser.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/hpack_table.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/http2_settings.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/huffsyms.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/incoming_metadata.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/parsing.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/stream_lists.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/stream_map.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/varint.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/writing.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/alpn/alpn.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/http/client/http_client_filter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/http/http_filters_plugin.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/http/message_compress/message_compress_filter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/http/server/http_server_filter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/httpcli_security_connector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/context/security_context.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/composite/composite_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/credentials_metadata.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/fake/fake_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/google_default/credentials_generic.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/google_default/google_default_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/iam/iam_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/jwt/json_token.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/jwt/jwt_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/jwt/jwt_verifier.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/local/local_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/oauth2/oauth2_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/plugin/plugin_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/ssl/ssl_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/tls/grpc_tls_credentials_options.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/tls/spiffe_credentials.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/security_connector/alts/alts_security_connector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/security_connector/fake/fake_security_connector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/security_connector/load_system_roots_fallback.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/security_connector/load_system_roots_linux.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/security_connector/local/local_security_connector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/security_connector/security_connector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/security_connector/ssl/ssl_security_connector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/security_connector/ssl_utils.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/security_connector/tls/spiffe_security_connector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/transport/client_auth_filter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/transport/secure_endpoint.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/transport/security_handshaker.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/transport/server_auth_filter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/transport/target_authority_table.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/transport/tsi_error.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/util/json_util.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init_secure.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/crypt/aes_gcm.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/crypt/gsec.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/frame_protector/alts_counter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/frame_protector/alts_crypter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/frame_protector/alts_frame_protector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/frame_protector/alts_record_protocol_crypter_common.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/frame_protector/alts_seal_privacy_integrity_crypter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/frame_protector/alts_unseal_privacy_integrity_crypter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/frame_protector/frame_handler.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/alts_handshaker_client.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/alts_shared_resource.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/alts_tsi_handshaker.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/zero_copy_frame_protector/alts_grpc_integrity_only_record_protocol.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/zero_copy_frame_protector/alts_grpc_privacy_integrity_record_protocol.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/zero_copy_frame_protector/alts_grpc_record_protocol_common.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/zero_copy_frame_protector/alts_iovec_record_protocol.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/zero_copy_frame_protector/alts_zero_copy_grpc_protector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/check_gcp_environment.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/check_gcp_environment_linux.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/check_gcp_environment_no_op.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/check_gcp_environment_windows.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/grpc_alts_credentials_client_options.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/grpc_alts_credentials_options.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/grpc_alts_credentials_server_options.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/alts_handshaker_service_api.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/alts_handshaker_service_api_util.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/alts_tsi_utils.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/transport_security_common_api.o
      CC(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/altscontext.pb.o
      CC(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/handshaker.pb.o
      CC(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/alts/handshaker/transport_security_common.pb.o
      CC(target) Release/obj.target/grpc/deps/grpc/third_party/nanopb/pb_common.o
      CC(target) Release/obj.target/grpc/deps/grpc/third_party/nanopb/pb_decode.o
      CC(target) Release/obj.target/grpc/deps/grpc/third_party/nanopb/pb_encode.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/transport_security.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/client/authority.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/client/chttp2_connector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/backup_poller.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/channel_connectivity.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/client_channel.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/client_channel_channelz.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/client_channel_factory.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/client_channel_plugin.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/connector.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/global_subchannel_pool.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/health/health_check_client.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/http_connect_handshaker.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/http_proxy.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy_registry.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/local_subchannel_pool.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/parse_address.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/proxy_mapper.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/proxy_mapper_registry.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/resolver.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/resolver_registry.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/resolver_result_parsing.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/resolving_lb_policy.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/retry_throttle.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/server_address.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/service_config.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/subchannel.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/subchannel_pool_interface.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/deadline/deadline_filter.o
      CC(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/health/health.pb.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/fake_transport_security.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/local_transport_security.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/ssl/session_cache/ssl_session_boringssl.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/ssl/session_cache/ssl_session_cache.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/ssl/session_cache/ssl_session_openssl.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/ssl_transport_security.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/tsi/transport_security_grpc.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/client/secure/secure_channel_create.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/inproc/inproc_plugin.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/inproc/inproc_transport.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/client_load_reporting_filter.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb_channel_secure.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/grpclb_client_stats.o
      CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.o
    make: Leaving directory '/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/build'
    Failed to execute '/home/zyf/.nvm/versions/node/v10.17.0/bin/node /tmp/etcdmanager/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1' (1)
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@0.13.0
    node-pre-gyp info using node@10.17.0 | linux | x64
    node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/electron-v6.1-linux-x64-glibc.tar.gz
    node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/electron-v6.1-linux-x64-glibc.tar.gz
    node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/electron-v6.1-linux-x64-glibc.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for grpc@1.22.2 and electron@6.1.4 (electron-v6.1 ABI, glibc) (falling back to source compile with node-gyp)
    node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/electron-v6.1-linux-x64-glibc.tar.gz
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@10.17.0 | linux | x64
    gyp info ok
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@10.17.0 | linux | x64
    gyp info spawn /usr/bin/python2
    gyp info spawn args [ '/tmp/etcdmanager/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/tmp/etcdmanager/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/zyf/.electron-gyp/6.1.4/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/zyf/.electron-gyp/6.1.4',
    gyp info spawn args   '-Dnode_gyp_dir=/tmp/etcdmanager/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/home/zyf/.electron-gyp/6.1.4/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info ok
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@10.17.0 | linux | x64
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    In file included from /usr/include/string.h:494,
                     from ../deps/grpc/third_party/nanopb/pb.h:68,
                     from ../deps/grpc/third_party/nanopb/pb_decode.h:9,
                     from ../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:21:
    In function ‘char* strncpy(char*, const char*, size_t)’,
        inlined from ‘grpc_grpclb_request* grpc_grpclb_request_create(const char*)’ at ../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:74:11:
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 128 equals destination size [-Werror=stringop-truncation]
      106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
          |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1plus: all warnings being treated as errors
    make: *** [grpc.target.mk:503: Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/tmp/etcdmanager/node_modules/node-gyp/lib/build.js:262:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
    gyp ERR! System Linux 5.3.0-23-generic
    gyp ERR! command "/home/zyf/.nvm/versions/node/v10.17.0/bin/node" "/tmp/etcdmanager/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v6.1"
    gyp ERR! cwd /tmp/etcdmanager/node_modules/etcd3/node_modules/grpc
    gyp ERR! node -v v10.17.0
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute '/home/zyf/.nvm/versions/node/v10.17.0/bin/node /tmp/etcdmanager/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/etcdmanager/node_modules/etcd3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    node-pre-gyp ERR! System Linux 5.3.0-23-generic
    node-pre-gyp ERR! command "/home/zyf/.nvm/versions/node/v10.17.0/bin/node" "/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
    node-pre-gyp ERR! cwd /tmp/etcdmanager/node_modules/etcd3/node_modules/grpc
    node-pre-gyp ERR! node -v v10.17.0
    node-pre-gyp ERR! node-pre-gyp -v v0.13.0
    node-pre-gyp ERR! not ok
    error Command failed with exit code 1.

                    command=/home/zyf/.nvm/versions/node/v10.17.0/bin/node /usr/share/yarn/bin/yarn.js run install
                    workingDir=/tmp/etcdmanager/node_modules/etcd3/node_modules/grpc
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by gtamas** [comment]
@zyf0330 

Thanks for reporting the problem, we are working on it. We'll keep you posted.
In the meantime, could you try the AppImage? 

Installing that should be better anyway, since it supports automated updates, while the snap package doesn't (yet).

Could you please give it a try and post your findings here?

Thanks in advance!

**Comment by zyf0330** [comment]
I have test appimage v1.0.0, it works. Very good product.

**Comment by gtamas** [comment]
@zyf0330 

Thanks, glad to hear you like it and it works fine! :)
We gonna fix the snap package soon and will publish a new release.

**Comment by gtamas** [comment]
@zyf0330 
We have released a new snap, which should work with more Linux distros. It seems the problem is solved. Closing this, please reopen if needed.

**Comment by zyf0330** [comment]
@gtamas I test the newest snap package v1.2.0 but it still doesn't open and exit with code 1.
